#!/usr/bin/env python3
"""
Shared example argument payloads and hints for Sensor Tower MCP tools.
"""

from __future__ import annotations

from typing import Any, Dict

# These examples are used both for metadata exposure and for unit/integration tests.
# Each record may include example arguments plus optional notes (e.g. skip reasons).

TOOL_ARGUMENT_EXAMPLES: Dict[str, Dict[str, Any]] = {'get_country_codes': {'arguments': {}},
 'get_category_ids': {'arguments': {'os': 'ios'}},
 'get_chart_types': {'arguments': {}},
 'health_check': {'arguments': {}},
 'get_app_metadata': {'arguments': {'os': 'ios', 'app_ids': '284882215', 'country': 'US'}},
 'top_in_app_purchases': {'arguments': {'os': 'ios', 'app_ids': '284882215', 'country': 'US'}},
 'get_download_estimates': {'arguments': {'os': 'ios',
                                          'app_ids': '284882215',
                                          'countries': 'US',
                                          'start_date': '2024-01-01',
                                          'end_date': '2024-01-07',
                                          'date_granularity': 'daily'}},
 'get_revenue_estimates': {'arguments': {'os': 'ios',
                                         'app_ids': '284882215',
                                         'countries': 'US',
                                         'start_date': '2024-01-01',
                                         'end_date': '2024-01-07',
                                         'date_granularity': 'daily'}},
 'compact_sales_report_estimates': {'arguments': {'os': 'ios',
                                                  'start_date': '2024-01-01',
                                                  'end_date': '2024-01-07',
                                                  'app_ids': '284882215',
                                                  'countries': 'US'}},
 'category_ranking_summary': {'arguments': {'os': 'ios', 'app_id': '284882215', 'country': 'US'}},
 'get_creatives': {'arguments': {'os': 'ios',
                                 'app_ids': '284882215',
                                 'start_date': '2024-01-01',
                                 'countries': 'US',
                                 'networks': 'Instagram',
                                 'ad_types': 'video'}},
 'get_impressions': {'arguments': {'os': 'ios',
                                   'app_ids': '284882215',
                                   'start_date': '2024-01-01',
                                   'end_date': '2024-01-07',
                                   'countries': 'US',
                                   'networks': 'Instagram',
                                   'date_granularity': 'daily'}},
 'impressions_rank': {'arguments': {'os': 'ios',
                                    'app_ids': '284882215',
                                    'start_date': '2024-01-01',
                                    'end_date': '2024-01-07',
                                    'countries': 'US',
                                    'networks': 'Instagram'}},
 'get_usage_active_users': {'arguments': {'os': 'ios',
                                          'app_ids': '284882215',
                                          'start_date': '2024-01-01',
                                          'end_date': '2024-01-07',
                                          'countries': 'US',
                                          'date_granularity': 'monthly'}},
'get_category_history': {'arguments': {'os': 'ios',
                                        'app_ids': '284882215',
                                        'category': '6005',
                                        'chart_type_ids': 'topfreeapplications',
                                        'start_date': '2024-01-01',
                                        'end_date': '2024-01-07',
                                        'countries': 'US'}},
 'app_analysis_retention': {'arguments': {'os': 'ios',
                                          'app_ids': '284882215',
                                          'date_granularity': 'monthly',
                                          'start_date': '2024-01-01'}},
 'downloads_by_sources': {'arguments': {'os': 'ios',
                                        'app_ids': '284882215',
                                        'countries': 'US',
                                        'start_date': '2024-01-01',
                                        'end_date': '2024-01-07'}},
 'app_analysis_demographics': {'arguments': {'os': 'ios',
                                             'app_ids': '284882215',
                                             'date_granularity': 'monthly',
                                             'start_date': '2024-01-01',
                                             'country': 'US'}},
 'app_update_timeline': {'arguments': {'os': 'ios', 'app_id': '284882215', 'country': 'US'}},
 'version_history': {'arguments': {'os': 'ios', 'app_id': '284882215', 'country': 'US'}},
 'get_featured_today_stories': {'arguments': {'country': 'US',
                                              'start_date': '2024-01-01',
                                              'end_date': '2024-01-07'}},
 'get_featured_apps': {'arguments': {'category': '6020',
                                     'country': 'US',
                                     'start_date': '2024-01-01',
                                     'end_date': '2024-01-07'}},
 'get_featured_creatives': {'arguments': {'os': 'ios',
                                          'app_id': '284882215',
                                          'countries': 'US',
                                          'start_date': '2024-01-01',
                                          'end_date': '2024-01-07'}},
 'get_keywords': {'arguments': {'os': 'ios', 'app_id': '284882215', 'country': 'US'}},
 'get_reviews': {'arguments': {'os': 'ios',
                               'app_id': '284882215',
                               'country': 'US',
                               'start_date': '2024-01-01',
                               'end_date': '2024-01-07',
                               'limit': 20}},
 'research_keyword': {'arguments': {'os': 'ios',
                                    'term': 'social',
                                    'country': 'US',
                                    'app_id': 284882215}},
 'get_category_rankings': {'arguments': {'os': 'ios',
                                         'category': '6005',
                                         'chart_type': 'topfreeapplications',
                                         'country': 'US',
                                         'date': '2024-01-01'}},
'get_top_and_trending': {'arguments': {'os': 'ios',
                                        'comparison_attribute': 'absolute',
                                        'time_range': 'week',
                                        'measure': 'units',
                                        'category': 6005,
                                        'date': '2024-01-01',
                                        'regions': 'US',
                                        'device_type': 'total'}},
 'get_top_publishers': {'arguments': {'os': 'ios',
                                      'comparison_attribute': 'absolute',
                                      'time_range': 'month',
                                      'measure': 'revenue',
                                      'category': 6005,
                                      'date': '2024-01-01',
                                      'country': 'US'}},
 'usage_top_apps': {'arguments': {'os': 'ios',
                                  'comparison_attribute': 'absolute',
                                  'time_range': 'month',
                                  'measure': 'DAU',
                                  'date': '2024-01-01',
                                  'regions': 'US'}},
 'get_store_summary': {'arguments': {'os': 'ios',
                                     'categories': '6014',
                                     'start_date': '2024-01-01',
                                     'end_date': '2024-01-07',
                                     'date_granularity': 'daily',
                                     'countries': 'US'}},
 'top_apps': {'arguments': {'os': 'ios',
                            'role': 'advertisers',
                            'date': '2024-01-01',
                            'period': 'month',
                            'category': 6005,
                            'country': 'US',
                            'network': 'Admob'}},
 'top_apps_search': {'arguments': {'os': 'ios',
                                   'app_id': '284882215',
                                   'role': 'advertisers',
                                   'date': '2024-01-01',
                                   'period': 'month',
                                   'category': 6005,
                                   'country': 'US',
                                   'network': 'Admob'}},
 'top_creatives': {'arguments': {'os': 'ios',
                                 'date': '2024-01-01',
                                 'period': 'month',
                                 'category': 6005,
                                 'country': 'US',
                                 'network': 'Youtube',
                                 'ad_types': 'video'}},
 'games_breakdown': {'arguments': {'os': 'ios',
                                   'categories': '7001',
                                   'start_date': '2024-01-01',
                                   'end_date': '2024-01-07',
                                   'date_granularity': 'daily',
                                   'countries': 'US'}},
 'search_entities': {'arguments': {'os': 'ios',
                                   'entity_type': 'app',
                                   'term': 'weather',
                                   'limit': 5}},
 'get_publisher_apps': {'arguments': {'os': 'ios', 'publisher_id': '284882218', 'limit': 5}},
 'get_unified_publisher_apps': {'arguments': {'unified_id': '560c48b48ac350643900b82d'}},
 'get_app_ids_by_category': {'arguments': {'os': 'ios',
                                           'category': '6005',
                                           'start_date': '2024-01-01',
                                           'limit': 100}},
 'analytics_metrics': {'skip_reason': 'requires connected apps credentials'},
 'sources_metrics': {'skip_reason': 'requires connected apps credentials'},
 'sales_reports': {'skip_reason': 'requires connected apps credentials'},
 'unified_sales_reports': {'skip_reason': 'requires connected apps credentials'}}
